---
title: "README"
author: "Allison Davis Connelly & Sophia McKelvey"
date: "2026-05-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Out of the frying pan and into the freezer: sex differences in thermal tolerance lacking in livebearing species**
  AUTHORS: Sophia E. McKelvey, Cassidy Hawk, Eric N. Iverson, Michael J. Ryan, and Allison C. Davis

***
***

# **EXPERIMENTAL OVERVIEW:**
  ## **Purpose:** Our interest lies in whether sex-baised temperature tolerance exists in 3 livebearing fishes: sailfin mollies (*Poecilia latipinna*), Western mosquitofish (*Gambusia affinis*), and Panuco swordtails (*Xiphophorous nigrensis*). This stems from an observation of males dying when sampling during hot months but females surviving fine. 

  ## **Main Aims:**
    (1) compare female and male thermal tolerance across these three species of livebearing fishes (Family: Poeciliidae)
    (2) compare thermal tolerance across mating strategies within a single livebearing species (*X. nigrensis*)

  ## **Hypothesis:** Preexisting sex differences (e.g. sexually selected traits, size, behavior etc.) decrease resistance to environmental temperature change.

  ## **Predictions:**
    - Males of fish with elaborate traits have a narrower thermal tolerance--i.e. lower thermal maximums and higher thermal minimums--compared to females of these species.
    - Males of fish without elaborate traits will have a similar tolerance to females of the same species.
    - Males with traits used in courtship (i.e. bright coloration and elongated fins) have a narrower thermal tolerance compared to males that use coercion (within swordtails).

***
***

# **FILE STRUCTURE & DATA DESCRIPTION**

The three folders correspond to the three analyses used in this study (all Rmd files are annotated):
  1. Austin Daily Temperature: calculating the daily temperature rate increase and decrease for four years
    - Austin-Daily-Temps.Rmd
    - Ausin_temp-data.csv
    
    | STATION | DATE | HOUR | REPORT_TYPE | SOURCE | HourlyDryBulbTemperature
| :---: | :---: | :---: | :---: | :---: | :---: |
| Station ID | Recording date in M/D/YYYY | Recording time in H:MM:SS | Type of meteorological event | Data collection sub-system | Temperature in °C |
    
   * Station ID: Camp Mabry, Austin TX (USW00013958)
   * Type of meteorological event: 
    - FM-12: global World Meteorological Organization samples generated at synoptic hours (00:00, 06:00, 12:00, 18:00, UTC)
    - FM-15: standard scheduled hourly observations
    - FM-16: unschedules special reporting triggered by rapid weather changes
    * Source:
      - 220: hourly temperature collection failed, data backfilled using Automated Surface Observing System 5-minute Data archive
      - 223: data via United States Air Force Surface Weather Observations
      - 343: data via National Oceanic and Atmospheric Administration Surface Weather Observation
    
    
  2. Trial Rates: calculating the temperature rate increase and decrease acheived in our trials
    - CSV
    - RMD
  3. Thermal Tolerance Analysis: overall analysis testing for sex differences in thermal tolerance
    - csv
    - Final_temperature-analysis.Rmd
    
An additional folder -- Raw Data -- contains the raw excel files corresponding to each trial with additional trial notes, and the raw climatology data for the Austin Daily tempperature analysis.
